const seedQuestions=[
 {system:'פתולוגיה · כליות',q:'גבר בן 24 מגיע עם עייפות, המטוריה וירידה בתפוקת השתן כשבועיים לאחר זיהום בדרכי הנשימה. קריאטינין 4.1 mg/dL. בביופסיית כליה נראית התמונה המצורפת. איזה ממצא נוסף צפוי ביותר?',image:'assets/renal-histology.png',answers:['משקעי IgA במזנגיום','נוגדנים נגד הממברנה הבזאלית הגלומרולרית','משקעי C3 בלבד לאורך הקפילרות','היעדר משקעים באימונופלואורסנציה'],correct:1,explanation:'התמונה מראה סהר (crescent) בחלל באומן — ביטוי לנזק גלומרולרי מהיר וחמור. בשילוב דימום ריאתי או מחלה מבודדת בכליה, נוגדני anti‑GBM יוצרים צביעה לינארית של IgG לאורך הממברנה הבזאלית.',pearl:'Linear = anti‑GBM; granular = immune complex; pauci‑immune = ANCA.',wrong:['IgA גורמת לרוב לצביעה גרנולרית מזנגיאלית ולהמטוריה סמוכה לזיהום.','זו התשובה המתאימה: נוגדני anti‑GBM יוצרים דגם לינארי.','C3 בלבד מתאים יותר ל‑C3 glomerulopathy.','היעדר משקעים מתאים ל‑pauci‑immune RPGN הקשור ל‑ANCA.']},
 {system:'פרמקולוגיה · אוטונומי',q:'אישה בת 67 עם COPD מקבלת ipratropium. מהו המנגנון הישיר ביותר האחראי לשיפור בנשימה?',answers:['אגוניזם לקולטני β2','אנטגוניזם מוסקריני בדרכי האוויר','עיכוב phosphodiesterase‑5','חסימת קולטני H1'],correct:1,explanation:'Ipratropium הוא אנטגוניסט מוסקריני קצר טווח. חסימת M3 בשריר החלק של הברונכים מפחיתה כיווץ והפרשת ריר.',pearl:'Ipratropium = SAMA; tiotropium = LAMA. שניהם שימושיים במיוחד ב‑COPD.',wrong:['זהו מנגנון של albuterol.','נכון — חסימת M3 גורמת לברונכודילטציה.','PDE‑5 inhibitors משמשים ל‑ED וליתר לחץ דם ריאתי.','חסימת H1 מסייעת באלרגיה אך אינה המנגנון כאן.']},
 {system:'ביוכימיה · מטבוליזם',q:'תינוק בן 3 ימים מפתח הקאות, ישנוניות ובצקת מוחית לאחר התחלת האכלה. אמוניה גבוהה ו‑BUN נמוך. רמת orotic acid תקינה. איזה אנזים חסר?',answers:['Ornithine transcarbamylase','Carbamoyl phosphate synthetase I','Argininosuccinate lyase','UMP synthase'],correct:1,explanation:'היפראמונמיה מוקדמת עם orotic acid תקין מצביעה על חסר CPS I. בחסר OTC מצטבר carbamoyl phosphate בציטוזול והופך ל‑orotic acid.',pearl:'CPS I deficiency: hyperammonemia, low BUN, normal orotic acid; OTC: high orotic acid.',wrong:['בחסר OTC ה‑orotic acid גבוה.','נכון — CPS I הוא השלב המיטוכונדריאלי הראשון במעגל האוראה.','חסר זה גורם ל‑argininosuccinic aciduria ושיער שביר.','חסר UMP synthase גורם ל‑orotic aciduria ללא היפראמונמיה.']},
 {system:'מיקרוביולוגיה · חיידקים',q:'מטייל מפתח שלשול מימי ללא דם לאחר שתיית מים מזוהמים. הרעלן מגביר cAMP בתאי המעי. איזה שינוי מתרחש?',answers:['הפעלת adenylate cyclase דרך Gs','עיכוב שחרור acetylcholine','ביקוע 28S rRNA','הפעלת guanylate cyclase'],correct:0,explanation:'הרעלן היציב בחום של ETEC וכולרה פועלים במסלולים שונים; רעלן הכולרה וה‑LT של ETEC עושים ADP‑ribosylation ל‑Gs ומעלים cAMP, עם הפרשת כלור ומים.',pearl:'Cholera/ETEC LT → Gs → cAMP; ETEC ST → guanylate cyclase → cGMP.',wrong:['נכון — Gs נשאר פעיל ומעלה cAMP.','זהו מנגנון botulinum toxin.','זהו מנגנון Shiga toxin.','זהו מנגנון הרעלן היציב בחום של ETEC.']},
 {system:'פיזיולוגיה · לב',q:'במעבר פתאומי משכיבה לעמידה באדם בריא, איזה שינוי מתרחש תחילה?',answers:['עלייה בירי הברורצפטורים','ירידה בטונוס הסימפתטי','ירידה בהחזר הוורידי','עלייה מיידית בנפח הפעימה'],correct:2,explanation:'כוח הכבידה גורם לאיגום ורידי ברגליים, ולכן תחילה יורדים ההחזר הוורידי, ה‑preload ונפח הפעימה. רק לאחר מכן רפלקס הברורצפטורים מעלה טונוס סימפתטי.',pearl:'Standing: ↓ venous return → ↓ SV/MAP → ↓ baroreceptor firing → ↑ sympathetic tone.',wrong:['הירי דווקא יורד עקב ירידת הלחץ.','הטונוס הסימפתטי עולה כפיצוי.','נכון — זהו השינוי הראשוני.','נפח הפעימה יורד תחילה.']},
 {system:'אימונולוגיה',q:'ילד עם זיהומים חוזרים בחיידקים עטופים, שקדים חסרים ורמות נמוכות של כל סוגי האימונוגלובולינים. איזה פגם סביר?',answers:['כשל בהבשלה של תאי B','חסר C5–C9','פגם ב‑NADPH oxidase','חסר adenosine deaminase'],correct:0,explanation:'X‑linked agammaglobulinemia נגרמת ממוטציה ב‑BTK ועצירת הבשלת תאי B. לכן רקמת לימפה היקפית ושקדים קטנים או חסרים וכל האימונוגלובולינים נמוכים.',pearl:'BTK deficiency appears after 6 months, when maternal IgG wanes.',wrong:['נכון — מוטציית BTK עוצרת pre‑B cells.','חסר MAC גורם בעיקר לזיהומי Neisseria.','CGD מתבטאת בזיהומי catalase-positive וגרנולומות.','ADA deficiency גורם ל‑SCID עם פגיעה גם בתאי T.']}
];
const questions=buildQuestionBank(seedQuestions);
let state={index:0,total:15,correct:0,streak:0,points:0,selected:null,answered:false,saved:new Set(),seconds:90};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function showView(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+id).classList.add('active-view');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));window.scrollTo(0,0)}
$$('.nav-item').forEach(n=>n.onclick=()=>showView(n.dataset.view));
function startQuiz(mode='mixed') {questions.sort(()=>Math.random()-.5);state={...state,index:0,total:mode==='blitz'?5:15,correct:0,streak:0,points:0,selected:null,answered:false,seconds:90};$('#quizLabel').textContent=mode==='blitz'?'בליץ 5 דקות':mode==='systems'?'מערכת ממוקדת':'מיקס חכם';$('#qTotal').textContent=state.total;showView('practice');renderQuestion()}
$('#quickStart').onclick=()=>startQuiz();$('#goalPractice').onclick=()=>startQuiz('blitz');$$('.mode-card').forEach(c=>c.onclick=()=>startQuiz(c.dataset.mode));$$('.start-any').forEach(b=>b.onclick=()=>startQuiz());$$('.mini-play').forEach(b=>b.onclick=()=>startQuiz('systems'));$$('.session-list button').forEach(b=>b.onclick=()=>startQuiz('systems'));
function renderQuestion(){const q=questions[state.index%questions.length];state.selected=null;state.answered=false;$('#qNumber').textContent=state.index+1;$('#quizProgress').style.width=((state.index+1)/state.total*100)+'%';$('#systemTag').textContent=q.system;$('#questionText').textContent=q.q;$('#questionImageWrap').style.display=q.image?'block':'none';if(q.image)$('#questionImage').src=q.image;$('#answers').innerHTML=q.answers.map((a,i)=>`<button class="answer" data-i="${i}"><span class="answer-letter">${String.fromCharCode(65+i)}</span><span>${a}</span></button>`).join('');$$('.answer').forEach(b=>b.onclick=()=>{if(state.answered)return;$$('.answer').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selected=+b.dataset.i});$('#submitAnswer').disabled=false;$('#explanation').classList.remove('show');state.seconds=90}
$('#submitAnswer').onclick=()=>{if(state.selected===null){toast('צריך לבחור תשובה לפני שבודקים');return}const q=questions[state.index%questions.length];state.answered=true;const good=state.selected===q.correct;$$('.answer').forEach((b,i)=>{if(i===q.correct)b.classList.add('correct');else if(i===state.selected)b.classList.add('wrong')});if(good){state.correct++;state.streak++;state.points+=100+(state.streak*10);$('#resultIcon').textContent='✓';$('#resultTitle').textContent='בדיוק!';$('#resultSubtitle').textContent='תשובה נכונה · +'+(100+state.streak*10)+' נקודות'}else{state.streak=0;$('#resultIcon').textContent='×';$('#resultTitle').textContent='כמעט — בואו נחדד';$('#resultSubtitle').textContent='התשובה הנכונה מסומנת בירוק'}$('#correctCount').textContent=state.correct;$('#streakCount').textContent=state.streak+' 🔥';$('#pointsCount').textContent=state.points;$('#explanationText').textContent=q.explanation;$('#pearlText').textContent=q.pearl;$('#whyWrong').innerHTML=q.wrong.map((w,i)=>`<div class="why-row"><b>${String.fromCharCode(65+i)}.</b> ${w}</div>`).join('');$('#explanation').classList.add('show');$('#submitAnswer').disabled=true}
$('#nextQuestion').onclick=()=>{if(state.index+1>=state.total){toast(`הסשן הושלם: ${state.correct}/${state.total} נכונות · ${state.points} נקודות`);showView('home');$('#dailyDone').textContent=Math.min(40,34+state.total);return}state.index++;renderQuestion()};$('#closeExplanation').onclick=()=>$('#explanation').classList.remove('show');$('.back-home').onclick=()=>showView('home');
$('#saveQuestion').onclick=()=>{const id=state.index%questions.length;if(state.saved.has(id)){state.saved.delete(id);toast('השאלה הוסרה מהשמורים')}else{state.saved.add(id);toast('השאלה נשמרה לחזרה') }$('#saveQuestion').textContent=state.saved.has(id)?'♥ נשמרה':'♡ שמירה';$('#savedText').textContent=state.saved.size?`שמורות לך ${state.saved.size} שאלות לחזרה ממוקדת.`:'עדיין לא שמרת שאלות. לחיצה על הלב בזמן תרגול תשמור אותן כאן.'};
$$('.confidence button').forEach(b=>b.onclick=()=>{$$('.confidence button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
setInterval(()=>{if(!$('#practice').classList.contains('active-view')||state.answered)return;if(state.seconds>0)state.seconds--;const m=String(Math.floor(state.seconds/60)).padStart(2,'0'),s=String(state.seconds%60).padStart(2,'0');$('#timer').textContent=m+':'+s},1000);
$('#allSessions').onclick=()=>toast('היסטוריית הסשנים תיפתח בגרסה המלאה');
