(function(){
 const KEY='stepwise_history_v1',cfg=window.STEPWISE_SUPABASE||{},configured=/^https:\/\/.+\.supabase\.co$/.test(cfg.url)&&cfg.anonKey.length>20;
 let client=null,user=null,mode='login';
 const local=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
 const saveLocal=e=>{const h=local();h.unshift(e);localStorage.setItem(KEY,JSON.stringify(h.slice(0,5000)))};
 async function record(e){const row={id:crypto.randomUUID(),created_at:new Date().toISOString(),...e};saveLocal(row);if(client&&user){const {error}=await client.from('learning_events').insert({...e,user_id:user.id});if(error)console.warn('History sync deferred')}renderStats()}
 window.StepwiseBackend={record,renderStats};
 function metrics(rows){const qs=rows.filter(x=>x.event_type==='question'),bs=rows.filter(x=>x.event_type==='bite');const correct=qs.filter(x=>x.correct).length,known=bs.filter(x=>x.correct).length,days=new Set(rows.map(x=>x.created_at.slice(0,10))).size;return{total:rows.length,accuracy:qs.length?Math.round(correct/qs.length*100):0,mastery:bs.length?Math.round(known/bs.length*100):0,days}}
 async function getRows(){if(client&&user){const {data,error}=await client.from('learning_events').select('*').order('created_at',{ascending:false}).limit(5000);if(!error)return data}return local()}
 async function renderStats(){if(!document.querySelector('#statsTotal'))return;const rows=await getRows(),m=metrics(rows);$('#statsTotal').textContent=m.total;$('#statsAccuracy').textContent=m.accuracy+'%';$('#statsMastery').textContent=m.mastery+'%';$('#statsDays').textContent=m.days;const systems={};rows.forEach(r=>{if(!r.system)return;systems[r.system]??={n:0,c:0};systems[r.system].n++;if(r.correct)systems[r.system].c++});$('#systemStats').innerHTML=Object.entries(systems).sort((a,b)=>b[1].n-a[1].n).slice(0,8).map(([s,v])=>{const p=Math.round(v.c/v.n*100);return`<div class="system-row"><span>${s}</span><div class="system-bar"><i style="width:${p}%"></i></div><b>${p}%</b></div>`}).join('')||'<div class="empty-stats">התחילו לתרגל כדי לראות פילוח לפי מערכת.</div>';$('#historyList').innerHTML=rows.slice(0,8).map(r=>`<div class="history-item"><span class="history-icon">${r.event_type==='bite'?'⚡':'?'}</span><div><strong>${r.item_id||r.event_type}</strong><small>${r.system||''} · ${new Date(r.created_at).toLocaleDateString('he-IL')}</small></div><span class="history-result ${r.correct?'':'bad'}">${r.correct?'הצלחה':'לחזרה'}</span></div>`).join('')||'<div class="empty-stats">אין עדיין היסטוריה.</div>'}
 async function syncLocal(){if(!client||!user)return;const unsynced=local();if(unsynced.length){const rows=unsynced.map(({id,created_at,...e})=>({...e,user_id:user.id,created_at}));await client.from('learning_events').upsert(rows,{onConflict:'user_id,event_type,item_id,created_at',ignoreDuplicates:true})}}
 function authUI(session){user=session?.user||null;const btn=$('#authButton');btn.textContent=user?(user.email.split('@')[0]+' · יציאה'):'התחברות';btn.classList.toggle('signed',!!user);$('#syncBanner').textContent=user?'מסונכרן לחשבון Supabase':'מצב מקומי — ההתקדמות נשמרת במכשיר';$('#syncBanner').classList.toggle('connected',!!user)}
 async function init(){if(configured&&window.supabase){client=window.supabase.createClient(cfg.url,cfg.anonKey);const {data}=await client.auth.getSession();authUI(data.session);if(data.session){await syncLocal();renderStats()}client.auth.onAuthStateChange(async(_,session)=>{authUI(session);if(session)await syncLocal();renderStats()})}else authUI(null);renderStats()}
 $('#authButton').onclick=async()=>{if(user&&client){await client.auth.signOut();return}$('#authModal').classList.add('show');$('#authMessage').textContent=configured?'':'החיבור מוכן, אך עדיין חסרים פרטי פרויקט Supabase פעיל.'};$('#authClose').onclick=()=>$('#authModal').classList.remove('show');$$('.auth-tabs button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('.auth-tabs button').forEach(x=>x.classList.toggle('active',x===b));$('#authSubmit').textContent=mode==='login'?'התחברות':'יצירת חשבון'});$('#authSubmit').onclick=async()=>{if(!client){$('#authMessage').textContent='יש לפנות מקום לפרויקט Supabase חינמי ולהוסיף את פרטי החיבור.';return}const email=$('#authEmail').value,password=$('#authPassword').value;$('#authMessage').textContent='מתחבר…';const res=mode==='login'?await client.auth.signInWithPassword({email,password}):await client.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});$('#authMessage').textContent=res.error?res.error.message:(mode==='login'?'התחברת בהצלחה':'נשלח אימייל לאישור החשבון');if(!res.error&&mode==='login')$('#authModal').classList.remove('show')};
 const oldSubmit=$('#submitAnswer').onclick;$('#submitAnswer').onclick=function(e){const before=state.selected;oldSubmit.call(this,e);if(before!==null){const q=questions[state.index%questions.length];record({event_type:'question',item_id:q.id||`Q-${state.index}`,system:q.system,correct:before===q.correct,points:before===q.correct?100:0,metadata:{difficulty:q.difficulty||'seed',confidence:document.querySelector('.confidence .selected')?.dataset.confidence||'mid'}})}};
 const oldGrade=gradeBite;gradeBite=function(g){const b=currentBite();record({event_type:'bite',item_id:b.id,system:b.system,yield_level:b.yield,correct:g==='good'||g==='easy',points:g==='easy'?20:g==='good'?15:0,metadata:{grade:g,concept:b.concept}});oldGrade(g)};
 init();
})();
