/* Original educational generator: 18 concepts × 6 formats × 3 levels × 8 personas = 2,592 questions. */
const step1Concepts=[
{s:'ביוכימיה',t:'Von Gierke',f:'היפוגליקמיה קשה בצום, חמצת לקטית, היפראוריצמיה והגדלת כבד',q:'איזה אנזים חסר?',a:['Glucose-6-phosphatase','Acid α-glucosidase','Debranching enzyme','Muscle phosphorylase'],c:0,e:'חסר glucose-6-phosphatase מונע יצירת גלוקוז חופשי בכבד. G6P מצטבר ומנותב ללקטט, שומן וחומצת שתן.',p:'Von Gierke: severe fasting hypoglycemia + lactic acidosis + hepatomegaly.',w:['נכון — זהו החסר ב-Von Gierke.','Pompe גורמת קרדיומיופתיה והיפוטוניה.','Cori גורמת limit dextrins.','McArdle גורמת אי-סבילות למאמץ.']},
{s:'גנטיקה',t:'Hardy-Weinberg',f:'מחלה אוטוזומלית רצסיבית מופיעה ב-1 מתוך 10,000 לידות',q:'מהו בקירוב שיעור הנשאים?',a:['1/10,000','1/100','1/50','1/25'],c:2,e:'q²=1/10,000 ולכן q=1/100. כאשר p≈1, שיעור הנשאים הוא 2pq≈1/50.',p:'AR prevalence=q²; carrier frequency=2pq.',w:['זהו שיעור החולים.','זהו q, תדירות האלל.','נכון — 2×1×1/100.','זהו אומדן גבוה פי שניים.']},
{s:'אימונולוגיה',t:'CGD',f:'זיהומים חוזרים ב-S aureus, Serratia ו-Aspergillus עם בדיקת DHR חריגה',q:'איזה מנגנון פגום?',a:['NADPH oxidase','Myeloperoxidase','C5 convertase','BTK'],c:0,e:'ב-CGD חסר NADPH oxidase מונע respiratory burst. יצורים catalase-positive מפרקים H2O2 ולכן בולטים קלינית.',p:'CGD: catalase-positive organisms; abnormal DHR.',w:['נכון — פגם ב-respiratory burst.','MPO deficiency לרוב קלה.','חסר משלים טרמינלי קשור Neisseria.','BTK גורם agammaglobulinemia.']},
{s:'מיקרוביולוגיה',t:'Influenza shift',f:'זן שפעת חדש הופיע לאחר ערבוב מקטעי RNA מנגיף אנושי ונגיף עופות',q:'איזה תהליך התרחש?',a:['Antigenic drift','Antigenic shift','Reactivation','Transformation'],c:1,e:'Antigenic shift הוא reassortment של מקטעי influenza A ויוצר שינוי אנטיגני גדול המסוגל לגרום pandemic.',p:'Shift=reassortment; drift=point mutations.',w:['Drift הוא שינוי קטן ועונתי.','נכון — ערבוב מקטעים הוא shift.','Reactivation אינה ערבוב גנומים.','Transformation מתאר קליטת DNA בחיידק.']},
{s:'פתולוגיה',t:'Tumor suppressor',f:'בתא גידולי אבדו שני העותקים הפעילים של RB1',q:'איזה עיקרון מודגם?',a:['Gain of function','Two-hit hypothesis','Anticipation','Imprinting'],c:1,e:'גנים מדכאי גידול דורשים לרוב אובדן שני אללים ברמת התא. נשא תורשתי מתחיל עם hit אחד ולכן גידולים מופיעים מוקדם.',p:'Tumor suppressor: two hits; oncogene: one activating hit.',w:['Gain of function אופייני לאונקוגן.','נכון — אובדן שני אללים.','Anticipation נובע repeat expansion.','Imprinting תלוי בהורה המקור.']},
{s:'פרמקולוגיה',t:'Aminoglycosides',f:'מטופל מקבל gentamicin בשל זיהום גרם-שלילי קשה',q:'איזו תופעת לוואי אופיינית?',a:['Nephrotoxicity and ototoxicity','Gray baby syndrome','Tendon rupture','Hyperuricemia'],c:0,e:'Aminoglycosides נקשרים באופן בלתי הפיך ל-30S וגורמים misreading. רעילויות מרכזיות הן נפרוטוקסיות, אוטוטוקסיות וחסימה נוירומוסקולרית.',p:'Aminoglycosides require oxygen for uptake.',w:['נכון — אלו הרעילויות הקלאסיות.','Gray baby נגרם chloramphenicol.','Tendon rupture קשור fluoroquinolones.','Hyperuricemia אינה הרעילות המרכזית.']},
{s:'לב וכלי דם',t:'Aortic stenosis',f:'syncope במאמץ, angina ואוושה סיסטולית המקרינה לקרוטידים',q:'איזה שינוי בחדר שמאל צפוי?',a:['ירידה ב-afterload','עלייה ב-afterload והיפרטרופיה קונצנטרית','הרחבה אקסצנטרית בלבד','עלייה ב-compliance'],c:1,e:'היצרות אאורטלית יוצרת חסימה קבועה ומעלה afterload. החדר מפתח היפרטרופיה קונצנטרית ו-compliance יורד.',p:'Aortic stenosis: SAD—Syncope, Angina, Dyspnea.',w:['ה-afterload עולה.','נכון — pressure overload יוצר concentric hypertrophy.','Volume overload יוצר eccentric hypertrophy.','ה-compliance יורד.']},
{s:'ריאות',t:'Pulmonary embolism',f:'קוצר נשימה פתאומי לאחר ניתוח; אזור בריאה מאוורר אך אינו מקבל פרפוזיה',q:'מה קורה ליחס V/Q באזור?',a:['מתקרב לאפס','עולה ומתקרב לאינסוף','נשאר 0.8','שווה בדיוק ל-1'],c:1,e:'ב-PE האוורור נשמר והפרפוזיה יורדת, ולכן V/Q מתקרב לאינסוף—dead space. בשאנט V/Q מתקרב לאפס.',p:'PE=dead space; shunt=V/Q 0.',w:['אפס מתאים לשאנט.','נכון — ventilation without perfusion.','0.8 הוא הממוצע התקין.','אין סיבה שיהיה בדיוק 1.']},
{s:'כליות',t:'SIADH',f:'small cell lung cancer, נתרן 119, serum osmolality נמוכה ושתן מרוכז',q:'מהו מצב הנפח הסביר?',a:['Hypervolemic with edema','Euvolemic','Severely hypovolemic','Hyperosmolar dehydration'],c:1,e:'SIADH גורם אגירת מים קלה, אך natriuresis משני מונע בצקת משמעותית. לכן מדובר ב-euvolemic hypotonic hyponatremia.',p:'SIADH: euvolemic hyponatremia + concentrated urine.',w:['בצקת אינה אופיינית.','נכון — euvolemic קלינית.','זו אינה היפוולמיה.','האוסמולריות בסרום נמוכה.']},
{s:'גסטרואנטרולוגיה',t:'Celiac disease',f:'שלשול כרוני, ירידה במשקל, dermatitis herpetiformis וחסר ברזל',q:'איזה נוגדן הוא בדיקת הסקר המועדפת?',a:['Anti-mitochondrial','IgA anti-tTG','Anti-dsDNA','p-ANCA'],c:1,e:'IgA anti-tissue transglutaminase היא בדיקת הסקר המועדפת. מודדים גם total IgA ומאשרים בביופסיית תריסריון.',p:'Celiac: villous atrophy, crypt hyperplasia, intraepithelial lymphocytes.',w:['קשור ל-PBC.','נכון — anti-tTG IgA.','קשור ל-SLE.','יכול להופיע ב-UC.']},
{s:'אנדוקרינולוגיה',t:'Addison disease',f:'חולשה, ירידה במשקל, לחץ דם נמוך והיפרפיגמנטציה',q:'איזה פרופיל מעבדתי צפוי?',a:['Low ACTH, high cortisol','High ACTH, low cortisol','Low ACTH, low potassium','High cortisol, high aldosterone'],c:1,e:'בכשל אדרנלי ראשוני cortisol ו-aldosterone נמוכים. אובדן המשוב מעלה ACTH ו-MSH וגורם היפרפיגמנטציה.',p:'Primary Addison: low cortisol, high ACTH, hyperkalemia.',w:['אינו מתאים לכשל ראשוני.','נכון — הכשל בבלוטה עצמה.','ACTH והאשלגן עולים.','שני ההורמונים נמוכים.']},
{s:'נוירולוגיה',t:'Broca aphasia',f:'לאחר שבץ יש הבנה שמורה יחסית אך דיבור מאומץ במשפטים קצרים וחזרתיות פגועה',q:'איזה אזור נפגע?',a:['Dominant inferior frontal gyrus','Dominant superior temporal gyrus','Nondominant parietal lobe','Occipital cortex'],c:0,e:'Broca aphasia היא אפזיה לא-שוטפת עם הבנה שמורה יחסית, עקב פגיעה ב-inferior frontal gyrus הדומיננטי.',p:'Broca: broken speech; Wernicke: wordy but meaningless.',w:['נכון — זהו אזור Broca.','זהו אזור Wernicke.','פגיעה כאן גורמת neglect.','פגיעה כאן גורמת חסר ראייה.']},
{s:'המטולוגיה',t:'TTP',f:'בלבול, חום, פגיעה כלייתית, thrombocytopenia ו-schistocytes',q:'איזה אנזים חסר או מעוכב?',a:['ADAMTS13','G6PD','Factor VIII','Protein C'],c:0,e:'ירידה ב-ADAMTS13 מונעת ביקוע multimers גדולים של vWF וגורמת microthrombi עשירי טסיות, MAHA וטרומבוציטופניה.',p:'Treat suspected TTP urgently with plasma exchange.',w:['נכון — זהו מנגנון TTP.','G6PD גורם hemolysis oxidant.','Factor VIII גורם hemophilia A.','Protein C deficiency גורם thrombosis.']},
{s:'שלד ושריר',t:'Myasthenia gravis',f:'ptosis ודיפלופיה המחמירים בערב ומשתפרים במנוחה',q:'מהו אתר המטרה של הנוגדנים?',a:['Presynaptic Ca²⁺ channels','Postsynaptic nicotinic ACh receptors','Muscarinic receptors','Peripheral myelin'],c:1,e:'ב-MG נוגדנים פוגעים בקולטני nicotinic ACh פוסט-סינפטיים. החולשה מחמירה בשימוש וקיימת אסוציאציה ל-thymus.',p:'MG worsens with use; Lambert-Eaton may improve with activity.',w:['זהו Lambert-Eaton.','נכון — הקולטן הפוסט-סינפטי.','אינו קולטן NMJ של שריר שלד.','אינו מנגנון MG.']},
{s:'רבייה',t:'Ectopic pregnancy',f:'איחור במחזור, כאב חד חד-צדדי, דימום ו-β-hCG חיובי',q:'מהו אתר ההשתרשות השכיח ביותר?',a:['Cervix','Ampulla of fallopian tube','Ovary','Abdominal cavity'],c:1,e:'רוב ההריונות האקטופיים משתרשים ב-ampulla. גורמי סיכון כוללים PID, ניתוח חצוצרות, עישון והריון אקטופי קודם.',p:'Ectopic: unilateral pain + bleeding + positive hCG.',w:['אתר נדיר.','נכון — ה-ampulla שכיחה ביותר.','אתר נדיר.','נדיר מאוד.']},
{s:'פסיכיאטריה',t:'Serotonin syndrome',f:'שילוב SSRI ו-linezolid ולאחריו agitation, חום, clonus והיפררפלקסיה',q:'מהי האבחנה?',a:['Neuroleptic malignant syndrome','Serotonin syndrome','Malignant hyperthermia','Anticholinergic toxicity'],c:1,e:'Serotonin syndrome מופיעה במהירות לאחר שילוב תרופות סרוטונרגיות. clonus והיפררפלקסיה הם סימנים מבדילים.',p:'Serotonin: clonus; NMS: lead-pipe rigidity.',w:['NMS מאופיינת rigidity ומתפתחת לאט יותר.','נכון — עודף סרוטונרגי.','קשורה חומרי הרדמה.','גורמת עור יבש וירידה בקולות מעי.']},
{s:'ביוסטטיסטיקה',t:'Sensitivity',f:'בדיקת סקר שלילית למחלה מסכנת חיים ובעלת sensitivity גבוהה מאוד',q:'איזו מסקנה מתאימה?',a:['תוצאה שלילית מסייעת לשלול','תוצאה חיובית מוכיחה','אין false positives','ה-prevalence עולה'],c:0,e:'בדיקה בעלת sensitivity גבוהה מייצרת מעט false negatives. לכן תוצאה שלילית מסייעת לשלול—SnNout.',p:'SnNout; SpPin.',w:['נכון — מעט false negatives.','לכך נדרשת specificity גבוהה.','Sensitivity אינה מבטלת false positives.','הבדיקה אינה משנה prevalence.']},
{s:'אתיקה רפואית',t:'Capacity',f:'מטופל מסרב טיפול אך מבין מידע, מעריך השלכות, מנמק בחירה ומתקשר אותה',q:'מהי הפעולה המתאימה?',a:['לכפות טיפול','לכבד את הסירוב','לפנות אוטומטית לבית משפט','לבקש מהמשפחה לבטל'],c:1,e:'ארבעת מרכיבי capacity הם הבנה, הערכה, נימוק ותקשורת. מטופל בעל capacity רשאי לסרב גם לטיפול מציל חיים.',p:'Capacity is clinical and decision-specific; competence is legal.',w:['אין לכפות טיפול.','נכון — יש לכבד אוטונומיה.','אין צורך אוטומטי בבית משפט.','המשפחה אינה מבטלת החלטה תקפה.']}
];
function buildQuestionBank(seed=[]){const people=['ילד בן 8','נערה בת 16','גבר בן 24','אישה בת 31','גבר בן 45','אישה בת 58','גבר בן 67','אישה בת 72'];const forms=[(x,p)=>`${p} מגיע/ה עם ${x.f}. ${x.q}`,(x,p)=>`בחדר המיון נבדק/ת ${p}. הממצא המרכזי: ${x.f}. ${x.q}`,(x,p)=>`שאלת מנגנון: ${x.f}. ${x.q}`,(x,p)=>`בסבב מוצג/ת ${p} עם ${x.f}. ${x.q}`,(x,p)=>`איזה עיקרון מסביר: ${x.f}? ${x.q}`,(x,p)=>`בבחינת אינטגרציה מופיע/ה ${p}: ${x.f}. ${x.q}`];const levels=[['בסיסי','בחרו את התשובה היחידה הנכונה.'],['בינוני','זהו את הממצא המבדיל.'],['מתקדם','שלבו קליניקה ומנגנון.']];const out=[];let id=0;step1Concepts.forEach((x,xi)=>forms.forEach((form,fi)=>levels.forEach((lv,li)=>people.forEach((person,pi)=>{const r=(xi+fi+li+pi)%4,it=x.a.map((v,i)=>({v,i})),rot=it.slice(r).concat(it.slice(0,r)),correct=rot.findIndex(z=>z.i===x.c);out.push({id:`SW-${String(++id).padStart(4,'0')}`,system:x.s,difficulty:lv[0],type:['קלינית','מנגנון','אינטגרציה'][fi%3],topic:x.t,q:`${form(x,person)} ${lv[1]}`,answers:rot.map(z=>z.v),correct,explanation:x.e,pearl:x.p,wrong:rot.map(z=>x.w[z.i])})}))));return seed.concat(out)}
